name: dpsnn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.*
  - numpy >=1.16
  - pytorch
  - torchvision
  - cpuonly
  - tensorboard
  - matplotlib >=3.1
  - jupyterlab
  - ipywidgets
  - black
  - isort
  - tqdm
  - pip >=19
  - pip:
      - pytorch_lightning >= 0.7.*
      - -e .
